openapi: 3.0.0
info:
  title: Structures API
  version: 1.0.0

paths:
  /v1/healthcheck:
    get:
      summary: Health check
      responses:
        '200':
          description: OK

  /v1/users:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
      responses:
        '202':
          description: User successfully registered
    patch:
      summary: Update user details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
      responses:
        '200':
          description: User successfully updated

  /v1/users/activated:
    put:
      summary: Activate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
      responses:
        '200':
          description: User successfully activated

  /v1/users/password:
    put:
      summary: Update user password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                token:
                  type: string
      responses:
        '200':
          description: Password successfully updated

  /v1/tokens/authentication:
    post:
      summary: Create authentication token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Token successfully created

  /v1/projects:
    post:
      summary: Create new project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '201':
          description: Successfully created
    get:
      summary: List all projects
      responses:
        '200':
          description: A list of projects

  /v1/projects/{projectID}:
    get:
      summary: Get a project by ID
      parameters:
        - name: projectID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single project
    patch:
      summary: Update a project
      parameters:
        - name: projectID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '200':
          description: Successfully updated
    delete:
      summary: Delete a project
      parameters:
        - name: projectID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully deleted

  /v1/projects/{projectID}/invite:
    post:
      summary: Invite a user to a project
      parameters:
        - name: projectID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                permissions:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Invitation sent

  /v1/projects/{projectID}/units:
    post:
      summary: Create new unit
      parameters:
        - name: projectID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUnit'
      responses:
        '200':
          description: Successfully created

  /v1/projects/{projectID}/units/{unitID}:
    get:
      summary: Get a unit by ID
      parameters:
        - name: projectID
          in: path
          required: true
          schema:
            type: integer
        - name: unitID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single unit
    patch:
      summary: Update a unit
      parameters:
        - name: projectID
          in: path
          required: true
          schema:
            type: integer
        - name: unitID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Unit'
      responses:
        '200':
          description: Successfully updated
    delete:
      summary: Delete a unit
      parameters:
        - name: projectID
          in: path
          required: true
          schema:
            type: integer
        - name: unitID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully deleted

  /v1/projects/{projectID}/units/{unitID}/modules:
    post:
      summary: Create new module
      parameters:
        - name: projectID
          in: path
          required: true
          schema:
            type: integer
        - name: unitID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateModule'
      responses:
        '200':
          description: Successfully created

  /v1/projects/{projectID}/units/{unitID}/modules/{moduleID}:
    get:
      summary: Get a module by ID
      parameters:
        - name: projectID
          in: path
          required: true
          schema:
            type: integer
        - name: unitID
          in: path
          required: true
          schema:
            type: integer
        - name: moduleID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single module
    post:
      summary: Create a new version of a module
      parameters:
        - name: projectID
          in: path
          required: true
          schema:
            type: integer
        - name: unitID
          in: path
          required: true
          schema:
            type: integer
        - name: moduleID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateModule'
      responses:
        '200':
          description: Successfully created

components:
  schemas:
    CreateUser:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        image_url:
          type: string

    UpdateUser:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        image_url:
          type: string

    Project:
      type: object
      properties:
        name:
          type: string
        cep:
          type: string
        state:
          type: string
        city:
          type: string
        neighborhood:
          type: string
        street:
          type: string
        number:
          type: string
        phase:
          type: string
        description:
          type: string
        image_url:
          type: string
      required:
        - name
        - state
        - city
        - phase

    Unit:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          enum: ["tower"]
        total_floors:
          type: integer
        tower_floors:
          type: integer
        base_floors:
          type: integer
        basement_floors:
          type: integer
        type_floors:
          type: integer
        total_area:
          type: number
          format: float
      required:
        - name
        - type

    CreateUnit:
      allOf:
        - $ref: '#/components/schemas/Unit'

    Concrete:
      type: array
      minItems: 1
      items:
        type: object
        properties:
          fck:
            type: string
            enum: ["20", "25", "30", "35", "40", "45"]
          volume:
            type: number
            format: float
        required: [fck, volume]

    BeamColumn:
      type: object
      properties:
        concrete_columns:
          $ref: '#/components/schemas/Concrete'
        concrete_beams:
          $ref: '#/components/schemas/Concrete'
        concrete_slabs:
          $ref: '#/components/schemas/Concrete'
        steel_ca50:
          type: number
        steel_ca60:
          type: number
        form_columns:
          type: number
        form_beams:
          type: number
        form_slabs:
          type: number
        form_total:
          type: number
        column_number:
          type: integer
        avg_beam_span:
          type: integer
        avg_slab_span:
          type: integer
      required:
        - concrete_columns
        - concrete_beams
        - concrete_slabs
        - steel_ca50
        - steel_ca60

    ConcreteWall:
      type: object
      properties:
        concrete_walls:
          $ref: '#/components/schemas/Concrete'
        concrete_slabs:
          $ref: '#/components/schemas/Concrete'
        steel_ca50:
          type: number
        steel_ca60:
          type: number
        wall_thickness:
          type: number
        slab_thickness:
          type: number
        form_area:
          type: number
        wall_area:
          type: number
      required:
        - concrete_walls
        - concrete_slabs
        - steel_ca50
        - steel_ca60

    BasicModuleData:
      type: object
      properties:
        name:
          type: string
        structure_type:
          type: string
          enum:
            - "beam_column"
            - "concrete_wall"
        floor_repetition:
          type: integer
        floor_area:
          type: number
          format: float
        floor_height:
          type: number
          format: float
      required:
        - name
        - structure_type
        - floor_repetition
        - floor_area
        - floor_height

    CreateModule:
      allOf:
        - $ref: '#/components/schemas/BasicModuleData'
        - oneOf:
            - $ref: '#/components/schemas/BeamColumn'
            - $ref: '#/components/schemas/ConcreteWall'
