services:
  database:
    image: postgres:17.5
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pa55word
      - POSTGRES_USER=bipc
      - POSTGRES_DB=bipc
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/pg_hba.conf:ro
    command: [ '-c', 'hba_file=/etc/pg_hba.conf' ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U bipc" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    cpu_count: 2
    networks:
      bipc-system-network:
        ipv4_address: 10.5.0.2

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - 1025:1025 # SMTP
      - 8025:8025 # Web UI
    user: root
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - mailhog-maildir:/maildir
    networks:
      bipc-system-network:
        ipv4_address: 10.5.0.3

  api:
    image: localhost/bipc:latest
    pull_policy: never
    container_name: api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GOMAXPROCS
      - GOGC=off
      - GOMEMLIMIT
    command: [
      "-port=3000", "-url=localhost:3000", "-db-dsn=postgres://bipc:pa55word@10.5.0.2:5432/bipc?sslmode=disable", "-smtp-host=10.5.0.3", "-smtp-port=1025", "-smtp-sender=BIPC <no-reply@bipc.org.br>",
      "-cors-trusted-origins=http://localhost:5173"]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/v1/healthcheck || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 2s
    networks:
      bipc-system-network:
        ipv4_address: 10.5.0.4
    depends_on:
      - database
      - mailhog
  
volumes:
  database-data: {}
  mailhog-maildir: {}

networks:
  bipc-system-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24