name: Deploy to Production

on:
  pull_request:
    types: [closed]
    branches: [develop]
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.1

      - name: Build frontend
        run: make build/frontend

      - name: Build documentation
        run: make build/docs

      - name: Build backend
        run: make build/api

      - name: Deploy to stage
        env:
          SSH_PRIVATE_KEY_STAGE: ${{ secrets.SSH_PRIVATE_KEY_STAGE }}
          ENV_FILE_STAGE: ${{ secrets.ENV_FILE_STAGE }}
          DB_DSN_STAGE: ${{ secrets.DB_DSN_STAGE }}
        run: make -f Makefile.stage.mk stage/deploy/ci
